name: CloudSim CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Build Java (CloudSim Backend)
      run: mvn clean package
    
    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Docker Image
      run: docker build -t cloudsim-project:latest .
    
    - name: Run Docker Container & Verify Backend
      run: |
        docker run -d -p 8000:8000 --name cloudsim-container cloudsim-project:latest
        sleep 10
        curl -f http://localhost:8000/simulate || exit 1
        docker stop cloudsim-container
